f=open('apps/frontend/app/components/GuestWelcome.tsx', 'r', encoding='utf-8')
txt=f.read()
f.close()
txt = txt.replace("className={`aspect-square ${item.artCoverUrl ? 'bg-black' : 'bg-gradient-to-br from-purple-500 to-pink-500'}` }", "className={`aspect-square ${item.artCoverUrl ? '' : 'bg-gradient-to-br from-purple-500 to-pink-500'}` }")
txt = txt.replace("className={`w-full aspect-square ${item.coverUrl ? 'bg-black' : 'bg-gradient-to-br from-purple-500 to-pink-500'} rounded-lg mb-2`}", "className={`w-full aspect-square ${item.coverUrl ? '' : 'bg-gradient-to-br from-purple-500 to-pink-500'} rounded-lg mb-2`}")
f=open('apps/frontend/app/components/GuestWelcome.tsx', 'w', encoding='utf-8')
f.write(txt)
f.close()
print('done')