f=open('apps/frontend/app/components/GuestWelcome.tsx', 'r', encoding='utf-8')
txt=f.read()
f.close()
txt = txt.replace('className="aspect-square bg-gradient-to-br from-purple-500 to-pink-500"', 'className={`aspect-square ${item.artCoverUrl ? \'\' : \'bg-gradient-to-br from-purple-500 to-pink-500\'}` }')
txt = txt.replace('className="w-10 h-10 rounded-lg bg-gradient-to-br from-purple-500 to-pink-500 flex-shrink-0"', 'className={`w-10 h-10 rounded-lg ${track.artCoverUrl ? \'\' : \'bg-gradient-to-br from-purple-500 to-pink-500\'} flex-shrink-0`}`')
f=open('apps/frontend/app/components/GuestWelcome.tsx', 'w', encoding='utf-8')
f.write(txt)
f.close()
print('done')